### ISSUE TITLE
Thread pool test execution

### ISSUE THREAD

**Issue by rick-palmsens** [fixie/fixie#262] opened 2021-09-08 14:08 UTC
I'm trying to run tests in parallel on the thread pool, but it seems to break both the CLI as well as the visual studio test explorer.

The test explorer does either not run the tests or not show the results, and the CLI tool messes up the colors of the terminal.

#### TestProject
```csharp
public class TestProject : ITestProject
{
    public void Configure(TestConfiguration configuration, TestEnvironment environment)
    {
        configuration.Conventions.Add<DefaultDiscovery, ThreadPoolExecution>();
    }
}

```
#### Execution
```csharp
public class ThreadPoolExecution : IExecution
{
    public async Task Run(TestSuite testSuite)
    {
        ThreadPool.GetMinThreads(out var maxRunningTests, out _);
        var runningTests = new List<Task>();

        foreach (var test in testSuite.Tests)
        {
            while (runningTests.Count >= maxRunningTests)
            {
                runningTests.Remove(await Task.WhenAny(runningTests));
            }

            runningTests.Add(test.Run());
        }

        while (runningTests.Count > 0)
        {
            runningTests.Remove(await Task.WhenAny(runningTests));
        }
    }
}
```

#### Some tests to execute
```csharp
public class FooTests
{
    public async Task DelayedTest1()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest2()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest3()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest4()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest5()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest6()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest7()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest8()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest9()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
    public async Task DelayedTest10()
    {
        await Task.Delay(TimeSpan.FromSeconds(1));
    }
}
```

## Expected Behavior
Fixie can run tests in parallel.

#### Not running the tests properly
![FixieParallel](https://user-images.githubusercontent.com/57390463/132524107-39e307f2-a9a4-48e2-85b2-07c5e0dd266b.gif)

#### Turning everything green
![FixieParallelConsole](https://user-images.githubusercontent.com/57390463/132524815-e4d00bd4-a250-4fc8-ba41-0f1f778d9894.gif)

**Comment by plioi** [comment] 2021-09-09 03:56
Hi, thanks for the excellent repro case and the informative animations! I'm afraid my response will be a disappointing, "No, this isn't supported, but maybe someday." I've gone in circles trying to find the Right approach before commiting to something regrettable.

You're right that parallelism like this is not supported. It may be, someday, but there are some big challenges to solve there in the test runner itself, and solving them would compete against the benefits, at least in part. There are also a few philosophical differences this project has with alternatives like xUnit worth talking through.

First, let's get the "straw man argument" out of the way: some folks who think they want parallel tests think that threads are a magic "make stuff go faster" button, and I'm sure you'd agree they are not. There's always trade-offs. xUnit runs parallel by default, and still runs notably slower at the command line and in Test Explorer in https://github.com/fixie/fixie.benchmark. For context, that runs 50k empty tests, merely to measure the overhead of the xUnit runner vs Fixie runner. Surely we could craft a benchmark where the parallelism of xUnit is faster, but it's not a clear win as a general always-on option. I suspect a great deal of the time spent in the xUnit run in that repo is in the contention of marshalling results to the various report sinks.

Next, Fixie's sweet spot is in integration tests, such as those which would exercise a feature all the way to the database and back. Again, folks who think they want parallelism at the test level in these cases can really damage their experience, where it gets incredibly difficult to make a meaningful test that can also consistently pass with its "siblings" messing with the same database. Then they might start mocking their database interactions, resulting in a test suite that is fast, green, and constantly lying about whether the system works.

Next, for folks who have a naturally parallel friendly system-under-test, let's say lots of simple number crunching, I'd argue that other test frameworks have handed folks the wrong tool by implying that the "straw man agrument"'s magic button is at hand at the test level. Instead, a more sound model might be at the process level, for instance: some hypothetical version of "dotnet fixie" which takes the set of discovered tests and farms them out to a few processes, each running their subset as the perceived `TestSuite` object. Each running process has no shared mutable state across threads waiting to surprise the developer. Even here, farming out *tests* is the wrong unit (imagine someone's convention establishes NUnit-like long-lived stateful test classes); the right unit would be the class level. Someone with a carefully crafted build script might accomplish this today, using the --tests filter while invoking "dotnet fixie" multiple times.

Next, some folks who think they want parallelism at the test level are in a situation when in their case they really want their sequential tests to fire off and await threads *themselves*. In other words, a test that kicks off the multithreaded running of some part of their system, ensures that all runs to completion, and then exits with its one test result that all that work completed successfully. There's a similar argument against "retry" conventions: does the developer really want the *test* to be retried, or rather do they want their single-run test to run-and-retry the *system under test* (such as with Polly) before deciding if the single test has succeeded.

In all these possible paths we run into a few concrete challenges in the implementation, all around the reporting mechanism. While your Execution class is running, particularly the moments where you call test.Run(), events are being emitted for reporting. "This one passed", "This one failed", etc. Those flow through the reporting infrastructure here: https://github.com/fixie/fixie/tree/6b6160305d3393ac6a3a7575b8c84f7ec3aec979/src/Fixie/Reports

Examples of some pains:

* Console capture and test timing would be broken. Folks might be willing to accept that if they opt into parallelism, though.
* `TeamCityReport` uses TeamCity's console output formatting opinions to detect results. If `TeamCityReport` weren't single threaded, it could easily interleave these output lines and break the reporting.
* `ConsoleReport` would have similar challenges.
* `AppVeyorReport` and `AzureReport` both need to hit APIs, and so there's some hope here that they might Just Work if hit across threads, but surely there's some gotchas around `AzureReprot`'s mutable state for the batching it does to avoid overloading Azure's test API. Some naive attempts here could seem perfectly sound in the implementation and then *regress* to a previous bug where messages would reach the Azure API so fast that it would start to throw 500s back at us.
* `XmlReport` would need to ultimately spend time carefully collecting results from each thread, and then spend time interleaving that data into the final file.
* Test Explorer is a particularly challenging nightmare in this regard. Here be dragons. The API we're stuck with is not async or threading friendly at all, and ultimately I'd expect that *it* needs us to submit messages to it in serial lockstep, introducing contention that would fight against the possible gains. In the benchmark mentioned above, the vast majority of the time spent is spent is in the interprocess communication back to VSTest in the single-threaded results method it exposes to us.

Overall, I think most of the options here are problems rather than solutions. The most likely path, really, would be for `dotnet fixie` to be able to farm out work to a few processes, each of which runs single-threaded with a subset of the overall discovered tests. Even here, though, it's not free: that's extra interprocess communication, extra work to interleave results like in the case of the `XmlReport`, etc. And anyone who makes a custom Report would have to take on the new burden of mutithreading awareness.

All in all, I do entertain the idea of some flavor of parallelism, but it's not clear that in-process parallelism is the answer, and it's not clear if the impact on sound reporting is worthwhile.

**Comment by rick-palmsens** [comment] 2021-09-14 08:24
I agree that just throwing threads at the problem isn't always the solution. In our case you can have one or more real devices connected your computer, that each can run their own set of tests which can take a long time. Running those in parallel would safe a lot of time. There are also unit tests that do no depend on each other at all, so running them in parallel would be completely safe and save a lot of time as well.

It is important to me that my team can run their tests quickly and often, so I think it is important to invest time in properly parallelizing the tests. The last thing I want is my team not running tests because they take too long.

So if I were to take a look at fixing this, would making the reporters (at least the ones that we use) thread safe fix these issues, or are there other components that are accessed in parallel?

**Comment by plioi** [comment] 2021-09-14 22:51
I just took a quick scan through the main Fixie project in the solution, looking for the main pain points.

I think an ideal solution for a quick win would be relatively small, and would not need a change to the Report types themselves. It'd be worth trying to get some `lock` or similar control around the *emitting* of messages to the reporting infrastructure and then all the reports might become stable "for free" as a side effect. A change involving updates to the actual Report types would be more likely to be the challenge we're always chasing from here on into the future.

So, here are the types that are pivotal to the Execution phase, which jump out to me either for their mutable state or for their proximity to that pivotal moment of "emit a result to be reported".

1. `Test`, the type of the main objects you are interacting with directly in your Execution class, has very little mutable state, but it'd be important to be sure we're not breaking it: the `RecordedResult` bool plays an important role in Fixie's ability to fully report things like skipped tests. The few times we set it are in tune with calls to the Test's **shared `ExecutionRecorder`**. More on that class below.
2. `ExecutionSummary` is a simple bag-of-ints tracking counts of each test result state. It's simple, but naturally heavily involved at the moment of a test completing and its result being recorded/reported. It's most "busy" *inside* the shared `ExecutionRecorder`.
3. `RecordingConsole` has some mutable state and likewise is mostly "busy" *inside* the shared `ExecutionRecorder`.
4. `ConsoleRedirectionBoundary` mutates state but I think this is all happening before and after Execution rather than during it.
5. `TestAdapterPipe` is not literally under the Reports folder but is very much a part of the `TestAdapterReport` (Test Explorer UI). Controlled access to the shared `ExecutionRecorder` probably lets us avoid touching this one.
6. `MethodInfoExtensions` is the workhorse for invoking a test method. Most of this appears safe already but we do technically have some shared mutable state in the static `startAsTask` field.
7. `ExecutionRecorder` is the scariest part of this from a thread safety point of view, but getting things right *here* probably *saves* us from having to make each individual Report care about threads. It's the "pinch point" where on the one side we want open ended parallelism and on the other side we want reliably sequential message processing. A shared instance of this class is referenced by all the `Test` objects so that they can announce pivotal events like TestStarted, TestSkipped, TestPassed, TestFailed... You'll see this is also where we play some mutable-state trickery to juggle recording console output and inferring test durations.
8. `Bus` is primarily hit *by* `ExecutionRecorder`. All roads lead to `Bus`, and it forwards messages to the registered Reports.

I don't know enough about using things like `lock` effecively, but if `ExecutionRecorder` itself were made to definitely run *its* methods in lockstep, that probably gets us 95% of the way there without having to make a lot of changes all over. Care around `Test.RecordedResult` setting probably gets us another 4% of the way there.

**Comment by rick-palmsens** [comment] 2021-09-17 07:22
We currently have a release coming up so I am a bit distracted, but I'll definitely take a look once I have time. And thank you for the details description of potential sources of concurrency issues, that will definitely help while I figure out where everything is.

**Comment by rick-palmsens** [comment] 2021-09-28 07:45
I made a pull request addressing some of the issues: #263

**Comment by RagingKore** [comment] 2023-12-12 11:30
Congrats on the project. Really great but this inability to run parallel async tests is a real issue. 

It has been a long time since the last time anyone commented on this.

I understand that it requires some work to re-write the recorder and rethink some other elements, yet I am more than willing to help if there are already some ideas on how to specifically implement this.

I can see how using bounded channels could help make things much easier per example.

**Comment by plioi** [comment] 2023-12-12 17:40
I agree this is important to the extent that Fixie should be stable in the face of custom `IExecution`s that run tests on multiple threads. I won't go so far as to advocate to the general public to run tests in parallel, but it's simply true that the current implementation isn't fair to those experts who are skilled with multithreading, who want to take on those trade-offs, and who would have the experience necessary to distinguish a remaining Fixie bug from a bug in their implementation of `IExecution`.

I fully recognize this is important, and when I think to myself, "Why am I not telling the world that this is the single test framework all .NET folks should be using on all their projects?", the answer is always precisely this issue. Someone will try it, hit flaky behavior, and set it aside forever.

I face two complications. This is going to fall under "How rude!" and "Yikes that's too much information!", but I'm finding that being slightly rude and offering up too much information has helped a bit in recent months.

1. First, the rude part. Offers of help in this area are not truly help, in the same sense that gifting a puppy to a coworker during this year's Secret Santa is not truly a gift, but an imposition that bafflingly ignores the ways that it is an imposition. Imagine it in detail: there's a thorny challenge that I have avoided for a decade out of concerns for correctness, despite being the single person on earth closely familiar enough with all the ins and outs of this codebase, and then a PR shows up that takes *the critical path of a test framework, the foundation the submitter intends for everyone to build all their own applications' correctness upon*, and casually tosses the critical path into a blender. It would leave me to both review it with a confidence that I clearly didn't have in the first place, and would leave me to answer to every novel bug report that follows whether those bugs are truly in Fixie or in the custom `IExecution`'s own imperfection. The puppy would be making a mess all over the carpet, and burning a hole in my credit card, eh? That isn't saving me time or effort or frustration, it doesn't aid my growth in understanding how to do it so well that I can advise the .NET community at large to switch, it doesn't grow my confidence that a sound answer exists, and it doesn't bring me closer to a solution that I can stake my career on.

2. Second, the "Too Much Information" part. For several confounding reasons and my own unskillful handling of them, I've faced overwhelming anxiety and depression for a little more than two years. Check the original Issue creation date above for an idea of how unfortunate that coincidence was for this feature. The project stalled right around that time. There's likely an undiagnosed additional pattern in the mix where the downstream side effect is to deeply believe that I cannot hold a critical train of thought from one moment to the next, despite evidence to the contrary. I've recently picked up some lighter work here to drag myself back up out of that depression, and by and large it's working by providing more evidence to my "lizard brain" that the cognition-distrust isn't grounded in facts. Working on this project in peace and silence, thinking about things one step at a time while setting all else aside, using the activity of working on it primarily to hone my craft and only secondarily to make a thing folks like, is the best thing for my mental state. I'd like to lock down all Issues and Pull Requests for a few months in the interest of succeeding, just to "lean in" to the fact that I Do The Thing when it is the Only Thing I'm Doing. I don't think GitHub settings offer that on public repos, though. Puppies are a feature, not a bug, it seems. A comment like this truly sets me back by about 2 days, partly because I just haven't been able to deal with simple things like that for a while, and partly because I'm writing this instead of working methodically and single-taskedly through the private roadmap.

I know it's weird. I get an email from an old colleague, I lose 2 days. I get a comment on a closed thread, I lose 2 days. I get an unanticipated PR, where the template pleading with folks to read the contribution guidelines is ignored so that being the bad guy and rejecting it becomes my problem, I lose 2 days. The result is wildly mismatched to the provoking event, but it's an unmistakable pattern I keep noticing in myself.

The direct path from offers-of-help and impositions-of-PRs to inactivity and frustration is not rational, I know. I do hate that my mind is doing that! I do not need folks to understand it, because it truly does not make sense. I do, however, need folks to believe it and to believe that working on this methodically in peace is the answer. That's why I'm being long-winded and oversharing here.

Ironic, that I'm facing a "multithreading bug" in my mind and that the solution for me is to insist on a bounded channel (capacity 1, multiple-producer, single-consumer, intense back pressure on writers 😂), in the work I'm doing here! Which brings me to the real news:

The strong interest in stability in the face of parallel `IExecutions`s, and the simple fact that it is blocking my ability to legitimately recommend Fixie to the .NET community, has been loud enough that I am adjusting my private roadmap.

1. I have some light, high-confidence tasks in progress on the v4 line right now that are warming me up to this kind of work, and I will wrap them up by approximately December 15.
2. Then I will switch to thread stability on the v4 line.
    * Yes, I'm looking at bounded channels as the approach I'm most likely to be able to fit in my brain. It looks to provide the kind of abstraction I need so that I'm not doing more manual things with locks or other multithreading primitives that leave me too concerned about creating a project-destroying bug magnet.
    * I'll pursue the multiple-producers, single-consumer style where the reporting sinks are on the consumer side of the divide. I'll be taking a full view of the entire solution while I do this in extremely careful steps, watching out for hidden gotchas like those suggested in the mutable state listing above. Surely the code has moved since then, so it'll be a fresh start on the train of thought.
    * Despite my rude rejection of "help", I may *at that time* be ready for help, and if so I'll open an issue to discuss whatever specific open questions I have at that time, pointing to the branch in progress. I'd invite interested parties, and would ask to keep the discussion to specific questions I have rather than opening up a disruptive design-by-committee.
    * I'll be keeping an eye out for finding a solution that would *not* be a breaking change with respect to v3. If so, then I'll go back to the latest v3 tag and back port it there, hopefully as the final v3 release. With v3 generally wrapping up, the goal there was stability for all existing supported features, so I'll only back port to v3 if it isn't likely to create new bug reports there. I'm more willing to do it in v4 where there's at least some expectation of breaking changes and beta testing, but I also want to avoid pressure to rush v4 development.
3. I'll link to this long-winded comment to more swiftly acknowledge and set aside new interruptions.

Thanks to everyone for their patience and for the generosity of their contributions over the last 10 years.

**Comment by plioi** [comment] 2024-10-24 22:02
Fixed in v4. Could not be safely applied in v3 due to the past poor design of console capture.

https://github.com/fixie/fixie/releases/tag/4.0.0

https://github.com/fixie/fixie/wiki/Customizing-the-Test-Project-Lifecycle#parallel-execution

**Closed by plioi** 2024-10-24 22:02 UTC
