### ISSUE TITLE
IDE Support

### ISSUE THREAD

**Issue by matthewblott** [fixie/fixie#227] opened 2020-07-05 17:03 UTC
I've read the documentation and it seems only Visual Studio is supported. Are there any plans to support other IDEs, in my case Jetbrains Rider?

Thanks :-)

(Apologies if this isn't the correct place to ask questions.)

**Comment by plioi** [comment] 2020-07-05 19:52
Thanks for the interest!

v3 is under development and part of our focus is on .NET 5, its cross-platform nature, and therefore naturally the ability to really use Fixie cross platform in the most common development environments (VS Code and Rider).

There is increasing hope that JetBrains has made this feasible. It would require a dedicated R#/Rider plug-in and all the dev and maintenance hours that implies, but their documentation makes it look like one *can* deal with the "impedence mismatch" between their existing test model and the model that Micrsoft's `dotnet test` uses behind the scenes. The plug-in apparently would focus on bridging that modeling gap. A colleague has expressed some interest in pursuing this, so I'd like to give that a little time before diving in myself.

I've updated the [Roadmap](https://github.com/fixie/fixie/wiki/Roadmap) to include this as it *has* been on my mind for the v3 time frame, which I hope arrives roughly around .NET 5. I'll close this Issue as a duplicate of the Roadmap item, but I welcome your input if there's anything further to discuss.

**Closed by plioi** 2020-07-05 19:52 UTC
