### ISSUE TITLE
TypeLoadException under Mono.

### ISSUE THREAD

**Issue by dragan** [fixie/fixie#72] opened 2014-12-18 16:13 UTC
The [transition](https://github.com/plioi/fixie/commit/5b9724a09869a13d4d2d66c7624768ee7fb35ea2) of moving the listeners to Fixie.Console, broke running under Mono. I'm not sure exactly why yet, but creating a ticket for reference. At first glance, I think it may be the MarshalByRefObject addition. I'm not sure how you're serializing, but private fields may not match under Mono.

In the meantime, I'm currently using Fixie 0.0.1.206 without any issues.

The Exception for reference, when running using the nuget package:
```
Fatal Error: System.TypeLoadException: Could not load type 'Fixie.ConsoleRunner.ConsoleListener, Fixie.Console, Version=0.0.1.222, Culture=neutral, PublicKeyToken=null'.

Server stack trace:
  at (wrapper managed-to-native) System.Type:internal_from_name (string,bool,bool)
  at System.Type.GetType (System.String typeName, Boolean throwOnError) [0x00000] in <filename unknown>:0
  at System.Runtime.Remoting.ObjRef..ctor (System.String typeName, System.String uri, IChannelInfo cinfo) [0x00000] in <filename unknown>:0
  at System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArgument (System.Object arg, System.Collections.ArrayList args) [0x00000] in <filename unknown>:0
  at System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArguments (System.Object[] arguments, System.Collections.ArrayList args) [0x00000] in <filename unknown>:0
  at System.Runtime.Remoting.Messaging.CADMethodCallMessage.GetArgs (System.Collections.ArrayList args) [0x00000] in <filename unknown>:0
  at System.Runtime.Remoting.Messaging.MethodCall..ctor (System.Runtime.Remoting.Messaging.CADMethodCallMessage msg) [0x00000] in <filename unknown>:0
  at System.AppDomain.ProcessMessageInDomain (System.Byte[] arrRequest, System.Runtime.Remoting.Messaging.CADMethodCallMessage cadMsg, System.Byte[]& arrResponse, System.Runtime.Remoting.Messaging.CADMethodReturnMessage& cadMrm) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.AppDomain:ProcessMessageInDomain (byte[],System.Runtime.Remoting.Messaging.CADMethodCallMessage,byte[]&,System.Runtime.Remoting.Messaging.CADMethodReturnMessage&)
  at System.Runtime.Remoting.Channels.CrossAppDomainSink.ProcessMessageInDomain (System.Byte[] arrRequest, System.Runtime.Remoting.Messaging.CADMethodCallMessage cadMsg) [0x00000] in <filename unknown>:0

Exception rethrown at [0]:

  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x00000] in <filename unknown>:0
```
When debugging, this is what is thrown:
```
exception	{System.TypeLoadException: Could not load type 'Fixie.Internal.ExecutionProxy'.

Server stack trace:
  at (wrapper managed-to-native) System.Reflection.Assembly:InternalGetType (System.Reflection.Assembly,System.Reflection.Module,string,bool,bool)
at System.Reflection.MonoAssembly.GetType (System.String name, Boolean throwOnError, Boolean ignoreCase) [0x00028] in /private/tmp/source-mono-mac-3.10.0-branch/bockbuild-mono-3.10.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.10.0/mcs/class/corlib/System.Reflection/MonoAssembly.cs:61
  at System.Activator.CreateInstance (System.String assemblyName, System.String typeName, Boolean ignoreCase, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityInfo) [0x0001c] in /private/tmp/source-mono-mac-3.10.0-branch/bockbuild-mono-3.10.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.10.0/mcs/class/corlib/System/Activator.cs:152
  at System.AppDomain.CreateInstance (System.String assemblyName, System.String typeName, Boolean ignoreCase, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00011] in /private/tmp/source-mono-mac-3.10.0-branch/bockbuild-mono-3.10.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.10.0/mcs/class/corlib/System/AppDomain.cs:389
  at System.AppDomain.CreateInstanceAndUnwrap (System.String assemblyName, System.String typeName, Boolean ignoreCase, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00000] in /private/tmp/source-mono-mac-3.10.0-branch/bockbuild-mono-3.10.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.10.0/mcs/class/corlib/System/AppDomain.cs:396
  at (wrapper remoting-invoke-with-check) System.AppDomain:CreateInstanceAndUnwrap (string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[])
  at (wrapper xdomain-dispatch) System.AppDomain:CreateInstanceAndUnwrap (object,byte[]&,byte[]&,string,string,bool)

Exception rethrown at [0]:

  at (wrapper xdomain-invoke) System.AppDomain:CreateInstanceAndUnwrap (string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[])
  at (wrapper remoting-invoke-with-check) System.AppDomain:CreateInstanceAndUnwrap (string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[])
  at Fixie.Execution.ExecutionEnvironment.Create[ExecutionProxy] (System.Object[] args) [0x00030] in /Users/dragan/Code/OpenSource/Fixie/src/Fixie/Execution/ExecutionEnvironment.cs:43
  at Fixie.Execution.ExecutionEnvironment.RunAssembly (Fixie.Options options, Listener listener) [0x00008] in /Users/dragan/Code/OpenSource/Fixie/src/Fixie/Execution/ExecutionEnvironment.cs:33
  at Fixie.ConsoleRunner.Program.Execute (System.String assemblyPath, Fixie.Options options) [0x00013] in /Users/dragan/Code/OpenSource/Fixie/src/Fixie.Console/Program.cs:120
  at Fixie.ConsoleRunner.Program.Main (System.String[] args) [0x00148] in /Users/dragan/Code/OpenSource/Fixie/src/Fixie.Console/Program.cs:54 }	System.TypeLoadException
```

**Comment by nathanboktae** [comment] 2015-01-06 06:40
+1 Also confirmed this. Considering ASP.NET vNext is cross platform, this is very critical. I really want to use this and not xUnit :(

**Comment by madhon** [comment] 2015-04-02 13:48
+2 on this, and its happening with v1.0.0.15

```
Fatal Error: System.TypeLoadException: Could not load type 'Fixie.ConsoleRunner.ConsoleListener, Fixie.Console, Version=1.0.0.15, Culture=neutral, PublicKeyToken=null'.
Server stack trace: 
  at (wrapper managed-to-native) System.Type:internal_from_name (string,bool,bool)
  at System.Type.GetType (System.String typeName, Boolean throwOnError) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.ObjRef..ctor (System.String typeName, System.String uri, IChannelInfo cinfo) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArgument (System.Object arg, System.Collections.ArrayList args) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArguments (System.Object[] arguments, System.Collections.ArrayList args) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.Messaging.CADMethodCallMessage.GetArgs (System.Collections.ArrayList args) [0x00000] in <filename unknown>:0 
  at System.Runtime.Remoting.Messaging.MethodCall..ctor (System.Runtime.Remoting.Messaging.CADMethodCallMessage msg) [0x00000] in <filename unknown>:0 
  at System.AppDomain.ProcessMessageInDomain (System.Byte[] arrRequest, System.Runtime.Remoting.Messaging.CADMethodCallMessage cadMsg, System.Byte[]& arrResponse, System.Runtime.Remoting.Messaging.CADMethodReturnMessage& cadMrm) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:ProcessMessageInDomain (byte[],System.Runtime.Remoting.Messaging.CADMethodCallMessage,byte[]&,System.Runtime.Remoting.Messaging.CADMethodReturnMessage&)
  at System.Runtime.Remoting.Channels.CrossAppDomainSink.ProcessMessageInDomain (System.Byte[] arrRequest, System.Runtime.Remoting.Messaging.CADMethodCallMessage cadMsg) [0x00000] in <filename unknown>:0 
Exception rethrown at [0]: 
  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x00000] in <filename unknown>:0 
```

**Comment by plioi** [comment] 2015-04-02 14:31
@madhon Just to be sure we're talking about the same thing, is this happening to you under mono, or is this similar looking exception happening outside of mono?

**Comment by madhon** [comment] 2015-04-02 19:43
It's mono running the build so it's happening under mono

**Comment by wallymathieu** [comment] 2015-04-03 19:28
- When I copied the testrunner and dlls from the lib folder into the bin/debug folder I got it to run fine. 
- When running from the lib folder or the solution path, the test runner failed. 

Could it be that an ilmerged exe would work without complication on mono?

**Comment by wallymathieu** [comment] 2015-04-05 00:56
Looks somewhat related to https://github.com/xunit/xunit/issues/158 but minus the threading issues.

**Comment by plioi** [comment] 2016-05-26 13:12
A few notes:

1. The work in-flight towards a 2.x release (the dev branch at the time of this writing) has a dramatically different approach to the use of AppDomains, and Listeners no longer inherit from MarshalByRefObject in that branch, which was the primary culprit here identified by the issue description above, so at a minimum Mono support would need to be retested after the first 2.x alpha gets published.

2. With .NET Core becoming the primary means of developing cross-platform .NET code, and considering the effort of supporting both .NET Core and Mono *forever*, .NET Core is the likely long-term winner that we can realistically focus on officially supporting in Fixie.

3. The serialization usages at the root of this issue are the result of Fixie's use of AppDomains. .NET Core deliberately excludes AppDomains, so the upcoming work to phase out the AppDomain dependency to run on .NET Core will in likely resolve this issue even for Mono.

Because this issue is the result of a dead/deprecated technology (AppDomains), and because that dependency is actively being gutted in the 2.x timeframe, I'm closing this issue.

**Closed by plioi** 2016-05-26 13:12 UTC
