### ISSUE TITLE
don't upgrade your VS 2017 to 15.8

### ISSUE THREAD

**Issue by RickTheHat** [fixie/fixie#192] opened 2018-08-16 01:34 UTC
## Steps to Reproduce
I upgraded my VS 2017 to the latest version 15.8.0

## Expected Behavior
I expect that my test project tests built using Fixie 1.0.2 would still show up in the test explorer

## Actual Behavior
In the test explorer window, my Fixie tests no longer appear

*** I did try to clear vsextension cache, I tried to upgrade to the latest Fixie, I removed Fixie & added it back in, I created a new project and added Fixie 1.02 & 2.01, I also made sure that in Tools > Options > Test that everything was checked but to no avail ***

**Comment by RickTheHat** [comment] 2018-08-16 13:43
I have not reported this to the VsTest team

**Comment by plioi** [comment] 2018-08-16 13:46
I'll try to reproduce the issue this evening on my personal machine, and then I'll submit a ticket if there's no evidence it's on Fixie's side.

**Comment by plioi** [comment] 2018-08-17 03:43
I can reproduce the issue, and have created https://github.com/Microsoft/vstest/issues/1736 as it appears to be an issue on the VSTest side. Tentatively closing *this* issue since the real discussion will be going on over in that repo.

**Closed by plioi** 2018-08-17 03:43 UTC

**Comment by plioi** [comment] 2018-08-29 00:06
@RickTheHat per the linked vstest issue, they advised that I **uncheck** Tools \ Options \ Test \ "For Improved performance..."

The phrasing of that checkbox is misleading in this context, but for my own steps to reproduce the issue, it worked.

**Comment by plioi** [comment] 2018-09-03 19:12
@RickTheHat the Tools \ Options \ Test checkbox workaround above should no longer be necessary after upgrading to Fixie 2.0.2.  Upgrade, restore the checkboxes to checked, and you should be back in business. Apologies for the delay: we needed to first confirm what had been changed on the VS side before we could be confident in making the right fix.
